# Generated by Django 5.1.2 on 2024-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_diagnosis_ef_prediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='prescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='symptoms',
            field=models.TextField(default=''),
        ),
    ]
