# Generated by Django 5.1.2 on 2024-11-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_diagnosis_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnosis',
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='patients.diagnosis')),
            ],
        ),
    ]
