# Generated by Django 5.1.4 on 2024-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_diagnosis_diagnosis_interpretation'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='view_type',
            field=models.CharField(choices=[('a4c', 'A4C'), ('psax', 'PSAX')], default='a4c', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
