# Generated by Django 5.1.4 on 2024-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_diagnosis_view_type_patient_height_patient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='ejection_fraction',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
